### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by imagejan** [cleterrier/ChrisLUTs#2]
Hi @cleterrier, thanks for sharing these LUTs.

I *assume* they're free to use, but would you care to add a license to the repository to make that explicit?

**Comment by cleterrier** [comment]
They are free to use. I'll see about a license

**Comment by swharden** [comment]
Yeah this is a rabbit hole. I've been researching this topic for a couple weeks in working on bundling colormaps with two repos I'm working on:
* https://github.com/swharden/ScottPlot
* https://github.com/swharden/Spectrogram

This is what I found:

### These are Free and Easy
`magma`, `inferno`, `plasma`, `viridis` are easy to pull from matplotlib for any purpose. Nice.
https://github.com/BIDS/colormap/blob/master/colormaps.py
They're based on
https://bids.github.io/colormap/

### Turbo is Almost Easy
`turbo` is easy to get but it's Apache licensed (permissive, but slightly different than MIT)
https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html (links at bottom)

### Avoid nasty colorbrewer colormap licenses in matplotlib
Other matplotlib colormaps have restrictive licenses, like the ones based on colorbrewer, which is awful because colorbrewer derived works require you to distribute its own silly custom license https://github.com/matplotlib/matplotlib/tree/master/LICENSE so hard pass 🙅 

Since I want to mimic "greens" and "blues" from matplotlib in my application, but they're based on colorbrewer and I don't want a rediculous colorbrewer license to infect my repo, I made a tool to help me generate a similar colormap from scratch using spline interpolation 😝 🙈 

### Please license this repo
So, @cleterrier, I love that you made this library but I agree with @imagejan that this project should have a clear (MIT) license, and each colormap should have a clear statement in its source code whether you made it or not (with ones not made by you maybe having restrictive licenses). I'll bet more people than just me land here looking for this stuff...

Hope it helps!

**Comment by cleterrier** [comment]
Hi,

I made the effort to source all the LUTs, clearly indicating if they are
made by me or not in the long "About..." text that is part of the source
code.

Regarding license, I don't have the knowledge about the subtleties of
licenses and some of them don't have a license. Thank you for your help
regarding a couple of them, if people want to help building up a
comprehensive license frame for all of them (including contacting the
authors listed in the About section) I'd be happy integrate as much
information as possible.



Le mer. 17 juin 2020 à 00:51, Scott W Harden <notifications@github.com> a
écrit :

**Comment by cleterrier** [comment]
Sorry I made a reply that was not relevant for this repository, as all the LUTs here are from me except Turbo that I only generated as an ImageJ LUT format. I will add an MIT license for the others in the Readme. Thank you for pointing to the Apache license of Turbo.

**Comment by cleterrier** [comment]
Here is what was added to the Readme:

All the LUTs in this repository except Turbo have been devised by me and are available under an [MIT license](https://choosealicense.com/licenses/mit/). I made an ImageJ LUT for Turbo based on the [Apache 2.0 license](https://choosealicense.com/licenses/apache-2.0/) of the [original work](https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html).

**Comment by swharden** [comment]
Thanks @cleterrier! This is great to hear, and I look forward to using these LUTs in some of my own projects. I created a PR (#3) to put this license information in the standard locations. 

Thanks again for sharing your LUTs, and good luck with your experiments!
Scott

**Comment by cleterrier** [comment]
Thanks for this! PR merged and issue closed
